CREATE TABLE USERS (
   ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(100) UNIQUE NOT NULL,
   CREATE_DT DATETIME(3) NOT NULL,
   MOD_DT DATETIME(3) NOT NULL
);

CREATE TABLE TODO (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  TODO VARCHAR(200) NOT NULL,
  PWD VARCHAR(255) NOT NULL,
  CREATE_DT DATETIME(3) NOT NULL,
  MOD_DT DATETIME(3) NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);